---


  - name: Run pre-tasks before apply
    include: prepatch_apply.yml
    tags: pre_tasks_before_apply

  - name: RAC Patching | RU to grid home first node (opatchauto)
    when: inventory_hostname in groups['racdb01']
    remote_user: "{{ root_user }}"
    shell: "export GRID_HOME={{ grid_home }}; export PATH=$GRID_HOME/bin:$GRID_HOME/OPatch:$PATH; {{ grid_home }}/OPatch/opatchauto apply {{ patch_dir }}/{{ patchid }} -oh {{ grid_home }} > {{ logdir }}/opatch_apply_gh_first.log 2>&1"
    register: patch_apply_gh_first

  - name: RAC Patching | RU to grid home second node (opatchauto)
    when: inventory_hostname in groups['racdb02']
    remote_user: "{{ root_user }}"
    shell: "export GRID_HOME={{ grid_home }}; export PATH=$GRID_HOME/bin:$GRID_HOME/OPatch:$PATH; {{ grid_home }}/OPatch/opatchauto apply {{ patch_dir }}/{{ patchid }} -oh {{ grid_home }} -nonrolling > {{ logdir }}/opatch_apply_gridhome_second.log 2>&1"
    register: patch_apply_gh_second

  - name: RAC Patching | Pause after GI patching completion
    pause: prompt="Verify First Node - Everything running OK or NOT." minutes=10

  - name: RAC Patching | RU to database home first node (opatchauto)
    when: inventory_hostname in groups['racdb01']
    remote_user: "{{ root_user }}"
    shell: "export ORACLE_HOME={{ oracle_home }}; export PATH=$ORACLE_HOME/bin:$ORACLE_HOME/OPatch:$PATH; {{ oracle_home }}/OPatch/opatchauto apply {{ patch_dir }}/{{ patchid }} -oh {{ oracle_home }} > {{ logdir }}/opatch_apply_oh_first.log 2>&1"
    register: patch_apply_oh_first

  - name: RAC Patching | RU to database home second node (opatchauto)
    when: inventory_hostname in groups['racdb02']
    remote_user: "{{ root_user }}"
    shell: "export ORACLE_HOME={{ oracle_home }}; export PATH=$ORACLE_HOME/bin:$ORACLE_HOME/OPatch:$PATH; {{ oracle_home }}/OPatch/opatchauto apply {{ patch_dir }}/{{ patchid }} -oh {{ oracle_home }} > {{ logdir }}/opatch_apply_oh_second.log 2>&1"
    register: patch_apply_oh_second

  - name: Run post-tasks after patch
    include: postpatch_apply.yml
    tags: post_tasks_after_apply

